export const KEYS = [
  'A Major',
  'A Minor',
  'A# Major',
  'A# Minor',
  'B Major',
  'B Minor',
  'C Major',
  'C Minor',
  'C# Major',
  'C# Minor',
  'D Major',
  'D Minor',
  'D# Major',
  'D# Minor',
  'E Major',
  'E Minor',
  'F Major',
  'F Minor',
  'F# Major',
  'F# Minor',
  'G Major',
  'G Minor',
  'G# Major',
  'G# Minor',
]

export const GENRES = ['Trap', 'BoomBap', 'Rage', 'Drill', 'Hip Hop', 'Pop', 'Rock', 'Jazz', 'Classical', 'Electronic', 'House', 'Techno']
