export const KEYS = [
  'A Major',
  'A Minor',
  'A# Major',
  'A# Minor',
  'B Major',
  'B Minor',
  'C Major',
  'C Minor',
  'C# Major',
  'C# Minor',
  'D Major',
  'D Minor',
  'D# Major',
  'D# Minor',
  'E Major',
  'E Minor',
  'F Major',
  'F Minor',
  'F# Major',
  'F# Minor',
  'G Major',
  'G Minor',
  'G# Major',
  'G# Minor',
]

export const GENRES = ['Trap', 'BoomBap', 'Rage', 'Drill', 'Hip Hop', 'Pop', 'Rock', 'Jazz', 'Classical', 'Electronic', 'House', 'Techno']

export const INSTRUMENTS = [
  'Drums',
  '808',
  'Synth',
  'Pad',
  'Lead',
  'Pluck',
  'Electric Guitar',
  'Acoustic Guitar',
  'Bass Guitar',
  'Piano',
  'Grand Piano',
  'Keyboard',
  'Violin',
  'Cello',
  'Strings',
  'Flute',
  'Saxophone',
  'Trumpet',
  'Vocal Chop',
  'Choir',
  'Vocal Sample',
]

export const MOODS = [
  'Happy',
  'Sad',
  'Energetic',
  'Relaxed',
  'Romantic',
  'Melancholic',
  'Angry',
  'Uplifting',
  'Calm',
  'Motivational',
  'Chill',
  'Introspective',
  'Euphoric',
  'Aggressive',
  'Dark',
  'Nostalgic',
  'Mysterious',
  'Hopeful',
  'Playful',
  'Sentimental',
  'Tense',
  'Excited',
  'Dreamy',
  'Epic',
  'Mellow',
  'Groovy',
  'Trippy',
  'Peaceful',
  'Surreal',
  'Funky',
]
export const PLATFORMS = ['facebook', 'instagram', 'soundcloud', 'youtube', 'twitter', 'tiktok', 'other']
